# railway.toml
[build
]
  command = "npm install"
  environment = "production"[deploy
]
  startCommand = "node server.js"
  healthcheckPath = "/"
  restartPolicy = "ON_FAILURE"[env
]
  NODE_ENV = "production"